"""empty message

Revision ID: 0f2a7d305e81
Revises: b55c81cfe4ad
Create Date: 2023-02-14 12:01:47.808652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2a7d305e81'
down_revision = 'b55c81cfe4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
