"""empty message

Revision ID: 19d02a24fea2
Revises: fac07f102bbc
Create Date: 2023-01-11 01:35:48.392010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d02a24fea2'
down_revision = 'fac07f102bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('linkedin')
        batch_op.drop_column('facebook')
        batch_op.drop_column('instagram')
        batch_op.drop_column('twitter')

    # ### end Alembic commands ###
