"""empty message

Revision ID: 3a2fe3a3e66f
Revises: bdcc3f5da088
Create Date: 2023-01-19 22:56:48.438476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2fe3a3e66f'
down_revision = 'bdcc3f5da088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kd_appopen_new', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('kd_appopen_return', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('kd_appdeadline_new', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('kd_appdeadline_return', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cl_appsubmission', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cl_feepaid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cl_electrequest', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cl_sendproductpic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cl_sendlogo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cl_sendbio', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cl_wifipassword', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('info_datestart', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('info_dateend', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('info_timestart', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('info_timeend', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('info_loadindatetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('info_loadoutdatetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('info_boothfee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('info_whatfeeincludes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_boothlocation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('info_wifiavailable', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('info_foodavailable', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('info_foodpurchase', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('eventid', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'master_list', ['eventid'], ['id'])
        batch_op.drop_column('appdate_return')
        batch_op.drop_column('masterlistid')
        batch_op.drop_column('appdate_new')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookingid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'booking', ['bookingid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bookingid')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appdate_new', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('masterlistid', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('appdate_return', sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'master_list', ['masterlistid'], ['id'])
        batch_op.drop_column('eventid')
        batch_op.drop_column('info_foodpurchase')
        batch_op.drop_column('info_foodavailable')
        batch_op.drop_column('info_wifiavailable')
        batch_op.drop_column('info_boothlocation')
        batch_op.drop_column('info_whatfeeincludes')
        batch_op.drop_column('info_boothfee')
        batch_op.drop_column('info_loadoutdatetime')
        batch_op.drop_column('info_loadindatetime')
        batch_op.drop_column('info_timeend')
        batch_op.drop_column('info_timestart')
        batch_op.drop_column('info_dateend')
        batch_op.drop_column('info_datestart')
        batch_op.drop_column('cl_wifipassword')
        batch_op.drop_column('cl_sendbio')
        batch_op.drop_column('cl_sendlogo')
        batch_op.drop_column('cl_sendproductpic')
        batch_op.drop_column('cl_electrequest')
        batch_op.drop_column('cl_feepaid')
        batch_op.drop_column('cl_appsubmission')
        batch_op.drop_column('kd_appdeadline_return')
        batch_op.drop_column('kd_appdeadline_new')
        batch_op.drop_column('kd_appopen_return')
        batch_op.drop_column('kd_appopen_new')

    # ### end Alembic commands ###
