"""empty message

Revision ID: 434a6063f4ca
Revises: 6923a145bf1f
Create Date: 2023-02-01 21:45:57.444712

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '434a6063f4ca'
down_revision = '6923a145bf1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_touched', sa.DateTime(), nullable=True))
        batch_op.drop_column('next_touch')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_touch', sa.DATETIME(), nullable=True))
        batch_op.drop_column('next_touched')

    # ### end Alembic commands ###
