"""empty message

Revision ID: 45fa81f780a9
Revises: fb4c8baffb50
Create Date: 2023-02-07 21:29:38.982054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fa81f780a9'
down_revision = 'fb4c8baffb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_boothfee', sa.Float(), nullable=True))
        batch_op.drop_column('info_boothfees')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_boothfees', sa.FLOAT(), nullable=True))
        batch_op.drop_column('info_boothfee')

    # ### end Alembic commands ###
