"""empty message

Revision ID: 4abe44b155f1
Revises: 3a2fe3a3e66f
Create Date: 2023-01-20 00:13:45.460137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abe44b155f1'
down_revision = '3a2fe3a3e66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookingid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'booking', ['bookingid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bookingid')

    # ### end Alembic commands ###
