"""empty message

Revision ID: 5a9b61291bd1
Revises: b8bb2974a3f4
Create Date: 2023-01-21 13:57:20.533309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9b61291bd1'
down_revision = 'b8bb2974a3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cl_interested', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('cl_interested')

    # ### end Alembic commands ###
