"""empty message

Revision ID: 606e64b80b16
Revises: ead394a14f59
Create Date: 2023-01-17 00:47:07.683124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606e64b80b16'
down_revision = 'ead394a14f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_holiday', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.drop_column('type_holiday')

    # ### end Alembic commands ###
