"""empty message

Revision ID: 6579dd94bd9c
Revises: 
Create Date: 2023-02-10 21:25:22.495961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6579dd94bd9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordernum', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('personfk', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'people', ['personfk'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('personfk')
        batch_op.drop_column('total')
        batch_op.drop_column('ordernum')

    # ### end Alembic commands ###
