"""empty message

Revision ID: 6923a145bf1f
Revises: 5a9b61291bd1
Create Date: 2023-02-01 21:44:40.469974

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6923a145bf1f'
down_revision = '5a9b61291bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_touch', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('next_touch')

    # ### end Alembic commands ###
