"""empty message

Revision ID: 74e71d4466d6
Revises: 285848b675a8
Create Date: 2023-01-10 23:27:06.924724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e71d4466d6'
down_revision = '285848b675a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dates_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.drop_column('dates_text')

    # ### end Alembic commands ###
