"""empty message

Revision ID: 8f63565f2e42
Revises: 606e64b80b16
Create Date: 2023-01-17 00:57:24.437101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f63565f2e42'
down_revision = '606e64b80b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_art', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.drop_column('type_art')

    # ### end Alembic commands ###
