"""empty message

Revision ID: b55c81cfe4ad
Revises: 6579dd94bd9c
Create Date: 2023-02-11 23:53:08.029451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55c81cfe4ad'
down_revision = '6579dd94bd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookingid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('bookingid')

    # ### end Alembic commands ###
