"""empty message

Revision ID: b8bb2974a3f4
Revises: 4abe44b155f1
Create Date: 2023-01-21 00:51:49.405633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bb2974a3f4'
down_revision = '4abe44b155f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cl_appapproved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('cl_appapproved')

    # ### end Alembic commands ###
