"""empty message

Revision ID: cf63eba5e67e
Revises: 0f2a7d305e81
Create Date: 2023-03-01 21:56:30.366378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf63eba5e67e'
down_revision = '0f2a7d305e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_line_item', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
