"""empty message

Revision ID: e3db14a1eac2
Revises: 434a6063f4ca
Create Date: 2023-02-01 21:48:00.821201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3db14a1eac2'
down_revision = '434a6063f4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_touch', sa.DateTime(), nullable=True))
        batch_op.drop_column('next_touched')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_touched', sa.DATETIME(), nullable=True))
        batch_op.drop_column('next_touch')

    # ### end Alembic commands ###
