"""empty message

Revision ID: ead394a14f59
Revises: 19d02a24fea2
Create Date: 2023-01-17 00:22:19.386288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead394a14f59'
down_revision = '19d02a24fea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_bazaar', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('type_flea', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('type_health', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('type_market', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.drop_column('type_market')
        batch_op.drop_column('type_health')
        batch_op.drop_column('type_flea')
        batch_op.drop_column('type_bazaar')

    # ### end Alembic commands ###
