"""empty message

Revision ID: eb46e88c1b63
Revises: 7b6f4b46ab4e
Create Date: 2023-03-02 23:04:19.243058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb46e88c1b63'
down_revision = '7b6f4b46ab4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_when', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('prep_when', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('print_when', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('post_when', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ready2ship', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ready2ship_when', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipped_when', sa.DateTime(), nullable=True))
        batch_op.drop_column('ready_ship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ready_ship', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_column('shipped_when')
        batch_op.drop_column('ready2ship_when')
        batch_op.drop_column('ready2ship')
        batch_op.drop_column('post_when')
        batch_op.drop_column('print_when')
        batch_op.drop_column('prep_when')
        batch_op.drop_column('confirmed_when')

    # ### end Alembic commands ###
