"""empty message

Revision ID: f8685f939b92
Revises: f2b848917cbe
Create Date: 2023-02-05 01:49:16.478947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8685f939b92'
down_revision = 'f2b848917cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_list', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
