"""empty message

Revision ID: fb4c8baffb50
Revises: f8685f939b92
Create Date: 2023-02-07 21:29:06.733534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4c8baffb50'
down_revision = 'f8685f939b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_boothfees', sa.Float(), nullable=True))
        batch_op.drop_column('info_boothfee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_boothfee', sa.FLOAT(), nullable=True))
        batch_op.drop_column('info_boothfees')

    # ### end Alembic commands ###
